name: Build

on: 
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
         update: true
         location: D:\
         msystem: mingw32
         install: >-
           base-devel 
           mingw-w64-i686-toolchain
           mingw-w64-i686-openssl
           mingw-w64-i686-zlib
           mingw-w64-i686-python-sphinx
           mingw-w64-i686-bzip2
           mingw-w64-i686-xz
           mingw-w64-i686-zstd
           mingw-w64-i686-cppdap
           mingw-w64-i686-python
           mingw-w64-i686-curl
           mingw-w64-i686-expat
           mingw-w64-i686-jsoncpp
           mingw-w64-i686-libarchive
           mingw-w64-i686-libuv
           mingw-w64-i686-ninja
           mingw-w64-i686-pkgconf
           mingw-w64-i686-rhash
           mingw-w64-i686-fc
           mingw-w64-i686-ncurses
           

      - name: Build CMake
        shell: msys2 {0}
        id: build
        run: |
          CMAKE_VERSION=3.31.4
          
          wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
          tar -zxf cmake-${CMAKE_VERSION}.tar.gz
          mkdir cmake
          mkdir build && cd build
          ../cmake-${CMAKE_VERSION}/bootstrap     \
              --prefix=../cmake                   \
              --generator="Unix Makefiles"        \
              --parallel=$(nproc)                 \
              --system-libs                       \
              --datadir=share/cmake               \
              --docdir=share/doc/cmake            \
              --mandir=share/man                  \
              --infodir=share/info                \
              --sphinx-info                       \
              --sphinx-man                        \
              --sphinx-html                       \
              --sphinx-qthelp                     \
              && make -j$(nproc) && make install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmake
          path: cmake
          compression-level: 9
