name: Build

on: 
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
         update: true
         location: D:\
         msystem: mingw32
         install: >-         
           git
           base-devel 
           mingw-w64-i686-gcc

      - name: Build CodeLite
        shell: msys2 {0}
        id: build
        run: |
          CMAKE_VERSION=3.31.4
          
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
          tar -zxf cmake-${CMAKE_VERSION}.tar.gz
          mkdir build && cd build
          ../cmake-${CMAKE_VERSION}/bootstrap && make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmake
          path: build
